[숨] 미션2 - qna 로그인기능 구현
code-squad/fe-set-qna-plain pull request #10
Opened 2019-11-11 15:21 UTC by developersoom

- useState를 이용해서 해보고 싶었는데 시간이 부족했습니다 😢
- async, await를 안쓰니 코드가 너무 지저분하네요.. `then 밭`... 
- 버튼 text 값 바꿀때 class 값으로 할까하다가 innerText가 좀 더 간편해보여서 그 방법으로 했습니다. 
- `todo` : 코드 리팩토링 / useState로 로그인 구현

그럼, 리뷰 부탁드려요. 감사합니당⭐️

2019-11-12 02:40 UTC, crongro requested changes
Promise를 조금더 공부해보세요!
then에 등록된 함수가 언제실행되는지, 그 함수의 반환값은 어디서 받게 되는지,
디버깅과 테스트를 하면서 fetch와 Promise패턴을 이번기회에 꼭 공부해보세요.

2019-11-12 02:40 UTC, crongro commented on public/qna.js
>        setQnAList(data => result.list || data);
왜 await 를 사용해야 할까요?  
res.json의 반환타입은 무엇일까요?

2019-11-12 02:40 UTC, crongro commented on public/qna.js
> +  if (token) isTokenValid(token) ? qnaService.initComponent() : '';
요코드는 이상합니다. 
isTokenValid()의 반환값이 뭐죠? 제가 볼때는 undefined가 반환되는 함수 같아요.

2019-11-12 02:40 UTC, crongro commented on public/qna.js
> +  $('.login-btn').addEventListener("click", () => $('.login-btn').innerText === '로그인' ? getLogin() : getLogout())
코드포매터를 사용하셨는지 이쁘게 변환되는 거 같았는데, 
이벤트핸들러는 분리되지 않고, addEventListener함수안에 한 줄로 표현이 되어 있네요.
분리하면 더 보기 좋을거 같습니다.

2019-11-12 02:40 UTC, crongro commented on public/qna.js
> +      if (data.auth) {
then체이닝과정에서 로직이 너무많아지면 가독성이 떨어지죠.
아래 부분을 함수로 분리하면 좋겠어요
```javascript
if (data.auth) {
        console.log(data.message, '로그인 되셨습니당...');
        localStorage.setItem('token', data.token);
        localStorage.setItem('username', fetchData.user);
        isSuccess = !isSuccess;
      } else {
        console.log('login: error')
      }
```

2019-11-12 02:40 UTC, crongro commented on public/qna.js
> +  $('.login-btn').innerText = "로그인";
text node값을 가지고 로그인됐는지, 안됐는지 확인하는 것말고 다른 방법이 어때요? 
텍스트는 변경이 될 수도 있고요.

적어도 className 을 사용하는 게 나아 보여요.

2019-11-12 02:40 UTC, crongro commented on public/qna.js
> +        return true;
여기 return은 어떤 함수에서 받는것일까요? 
제가볼때는 아무곳에서도 받지 못하는 반환값인거 같습니다.

2019-11-12 11:18 UTC, developersoom commented on public/qna.js
>        setQnAList(data => result.list || data);
promise 좀 더 공부해야겠어요!!

2019-11-12 11:18 UTC, developersoom commented on public/qna.js
> +  if (token) isTokenValid(token) ? qnaService.initComponent() : '';
흠,,, 수정해볼게요!

2019-11-12 11:18 UTC, developersoom commented on public/qna.js
> +  $('.login-btn').addEventListener("click", () => $('.login-btn').innerText === '로그인' ? getLogin() : getLogout())
넵, 갑자기 한 줄로 보고싶어서 제가 다 올렸어요 ㅎㅎ,,,

2019-11-12 11:18 UTC, developersoom commented on public/qna.js
> +      if (data.auth) {
네~!!!

2019-11-12 11:18 UTC, developersoom commented on public/qna.js
> +  $('.login-btn').innerText = "로그인";
token 유무로 파악해보도록 할게요!

2019-11-12 11:18 UTC, developersoom commented on public/qna.js
> +        return true;
콜백함수 개념으로 생각해야하는 거 같네요...? 수정해보겠습니다.

2019-11-12 15:04 UTC, developersoom commented
@crongro 수정했습니닷...!! 한번 더 검토 부탁드릴게요. 😃

2019-11-13 07:10 UTC, crongro approved these changes
수정하느라 고생하셨어요!
열정을 느낄 수 있어서 좋군요  ㅎ

2019-11-13 07:10 UTC, crongro commented on public/qna.js
> +    .then(data => data.authResult ? localStorage.setItem('username', data.id) : console.log('token-validation: error'))
네 수정했군요. 

참고로, 
isTokenValid에서 promise를 반환시킬 수도 있겠죠.
그렇게 전달되면, 받는쪽에서는 promise.then(returnResult => {...}); 이렇게 써야할거고요.

2019-11-13 07:10 UTC, crongro commented on public/qna.js
> +  if (token) isTokenValid(token);
이름을 바꿔야겠네요.  checkTokenValidation  정도가 어떨지..

2019-11-13 07:10 UTC, crongro commented on public/qna.js
> +  fetch(URL.VALIDATION, fetchData)
URL 이런식으로 분리한 거 좋네요.

2019-11-13 07:10 UTC, crongro commented on public/qna.js
> +        console.log('토큰이 유효하지 않습니다.');
console객체에는 warn이랑 error도 있으니 용도가 에러출력이면 요놈들을 사용해도 됩니다.

2019-11-13 07:10 UTC, merged